#Example configuration options that can be placed in your main SiriProxy config.yml

##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################

     - name: 'Isy99i'
       path: './plugins/siriproxy-isy99i'
       host: 'http://192.168.1.1' #IP address of the ISY-99i
       username: 'ISY-99i_Username'
       password: 'ISY-99i_Password'
       devices:
          - ["control room", "13%2037%20EA%201", 0]
          - ["night light|nightlight", "1A%20EB%20C%201", 1]

